/**
 * cloudwpss23-openapi-cyan
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * 
 */
export interface User {
    /**
     * Unique identifier for the given user.
     */
    id: any;

    firstName: any;

    lastName: any;

    email: any;

    dateOfBirth?: any;

    /**
     * Set to true if the user\'s email has been verified.
     */
    emailVerified: any;

    /**
     * The date that the user was created.
     */
    createDate?: any;

}
