"use strict";
/**
 * cloudwpss23-openapi-cyan
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DefaultApi = void 0;
var $ = require("jquery");
var configuration_1 = require("../configuration");
/* tslint:disable:no-unused-variable member-ordering */
var DefaultApi = /** @class */ (function () {
    function DefaultApi(basePath, configuration, defaultExtraJQueryAjaxSettings) {
        this.basePath = 'http://localhost:3000';
        this.defaultHeaders = [];
        this.defaultExtraJQueryAjaxSettings = undefined;
        this.configuration = new configuration_1.Configuration();
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
        if (defaultExtraJQueryAjaxSettings) {
            this.defaultExtraJQueryAjaxSettings = defaultExtraJQueryAjaxSettings;
        }
    }
    DefaultApi.prototype.extendObj = function (objA, objB) {
        for (var key in objB) {
            if (objB.hasOwnProperty(key)) {
                objA[key] = objB[key];
            }
        }
        return objA;
    };
    /**
     *
     * @summary
     * @param bucketName
     */
    DefaultApi.prototype.deleteV1BucketName = function (bucketName, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{name}'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling deleteV1BucketName.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'DELETE',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary
     * @param bucketName
     * @param fileName
     */
    DefaultApi.prototype.deleteV1FileName = function (bucketName, fileName, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{bucketname}/File/{filename}'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName))).replace('{' + 'FileName' + '}', encodeURIComponent(String(fileName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling deleteV1FileName.');
        }
        // verify required parameter 'fileName' is not null or undefined
        if (fileName === null || fileName === undefined) {
            throw new Error('Required parameter fileName was null or undefined when calling deleteV1FileName.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'DELETE',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary Your GET endpoint
     * @param bucketName
     */
    DefaultApi.prototype.getV1BucketName = function (bucketName, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{name}'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling getV1BucketName.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [
            'application/json'
        ];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'GET',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary Your GET endpoint
     */
    DefaultApi.prototype.getV1Buckets = function (extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Buckets';
        var queryParameters = {};
        var headerParams = {};
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [
            'application/json'
        ];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'GET',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary Your GET endpoint
     * @param bucketName
     * @param fileName
     */
    DefaultApi.prototype.getV1FileName = function (bucketName, fileName, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{bucketname}/File/{filename}'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName))).replace('{' + 'FileName' + '}', encodeURIComponent(String(fileName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling getV1FileName.');
        }
        // verify required parameter 'fileName' is not null or undefined
        if (fileName === null || fileName === undefined) {
            throw new Error('Required parameter fileName was null or undefined when calling getV1FileName.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [
            'application/json'
        ];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'GET',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary Your GET endpoint
     * @param bucketName
     */
    DefaultApi.prototype.getV1Files = function (bucketName, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{name}/Files'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling getV1Files.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [
            'application/json'
        ];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'GET',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary
     * @param bucketName
     */
    DefaultApi.prototype.optionsV1BucketName = function (bucketName, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{name}'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling optionsV1BucketName.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'OPTIONS',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary
     */
    DefaultApi.prototype.optionsV1Buckets = function (extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Buckets';
        var queryParameters = {};
        var headerParams = {};
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'OPTIONS',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary
     * @param bucketName
     * @param fileName
     */
    DefaultApi.prototype.optionsV1FileName = function (bucketName, fileName, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{bucketname}/File/{filename}'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName))).replace('{' + 'FileName' + '}', encodeURIComponent(String(fileName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling optionsV1FileName.');
        }
        // verify required parameter 'fileName' is not null or undefined
        if (fileName === null || fileName === undefined) {
            throw new Error('Required parameter fileName was null or undefined when calling optionsV1FileName.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'OPTIONS',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary
     * @param bucketName
     */
    DefaultApi.prototype.optionsV1Files = function (bucketName, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{name}/Files'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling optionsV1Files.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [];
        // to determine the Accept header
        var produces = [];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        var requestOptions = {
            url: localVarPath,
            type: 'OPTIONS',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     * Set permissions of bucket
     * @summary
     * @param bucketName
     * @param modelsPermission
     */
    DefaultApi.prototype.patchV1BucketName = function (bucketName, modelsPermission, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{name}'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling patchV1BucketName.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [
            'application/json'
        ];
        // to determine the Accept header
        var produces = [];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        headerParams['Content-Type'] = 'application/json';
        var requestOptions = {
            url: localVarPath,
            type: 'PATCH',
            headers: headerParams,
            processData: false
        };
        requestOptions.data = JSON.stringify(modelsPermission);
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary
     * @param bucketName
     * @param postV1BucketNameRequest
     */
    DefaultApi.prototype.postV1BucketName = function (bucketName, postV1BucketNameRequest, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{name}'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName)));
        var queryParameters = {};
        var headerParams = {};
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling postV1BucketName.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        // to determine the Content-Type header
        var consumes = [
            'application/json'
        ];
        // to determine the Accept header
        var produces = [
            'application/json'
        ];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        headerParams['Content-Type'] = 'application/json';
        var requestOptions = {
            url: localVarPath,
            type: 'POST',
            headers: headerParams,
            processData: false
        };
        requestOptions.data = JSON.stringify(postV1BucketNameRequest);
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    /**
     *
     * @summary
     * @param bucketName
     * @param fileName
     * @param data
     */
    DefaultApi.prototype.putV1FileName = function (bucketName, fileName, data, extraJQueryAjaxSettings) {
        var localVarPath = this.basePath + '/v1/Bucket/{bucketname}/File/{filename}'.replace('{' + 'BucketName' + '}', encodeURIComponent(String(bucketName))).replace('{' + 'FileName' + '}', encodeURIComponent(String(fileName)));
        var queryParameters = {};
        var headerParams = {};
        var formParams = new FormData();
        var reqHasFile = false;
        // verify required parameter 'bucketName' is not null or undefined
        if (bucketName === null || bucketName === undefined) {
            throw new Error('Required parameter bucketName was null or undefined when calling putV1FileName.');
        }
        // verify required parameter 'fileName' is not null or undefined
        if (fileName === null || fileName === undefined) {
            throw new Error('Required parameter fileName was null or undefined when calling putV1FileName.');
        }
        localVarPath = localVarPath + "?" + $.param(queryParameters);
        reqHasFile = true;
        formParams.append("data", data);
        // to determine the Content-Type header
        var consumes = [
            'multipart/form-data'
        ];
        // to determine the Accept header
        var produces = [];
        // authentication (bearer) required
        // oauth required
        if (this.configuration.accessToken) {
            var accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headerParams['Authorization'] = 'Bearer ' + accessToken;
        }
        if (!reqHasFile) {
            headerParams['Content-Type'] = 'application/x-www-form-urlencoded';
        }
        var requestOptions = {
            url: localVarPath,
            type: 'PUT',
            headers: headerParams,
            processData: false
        };
        if (headerParams['Content-Type']) {
            requestOptions.contentType = headerParams['Content-Type'];
        }
        requestOptions.data = formParams;
        if (reqHasFile) {
            requestOptions.contentType = false;
        }
        if (extraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, extraJQueryAjaxSettings);
        }
        if (this.defaultExtraJQueryAjaxSettings) {
            requestOptions = Object.assign(requestOptions, this.defaultExtraJQueryAjaxSettings);
        }
        var dfd = $.Deferred();
        $.ajax(requestOptions).then(function (data, textStatus, jqXHR) {
            return dfd.resolve({ response: jqXHR, body: data });
        }, function (xhr, textStatus, errorThrown) {
            return dfd.reject({ response: xhr, errorThrown: errorThrown });
        });
        return dfd.promise();
    };
    return DefaultApi;
}());
exports.DefaultApi = DefaultApi;
